### ISSUE TITLE
Unable to load DLL 'librtlsdr' or one of its dependencies: The specified module could not be found. (0x8007007E)

### ISSUE THREAD

**Issue by FossaMalaEnt** [nandortoth/rtlsdr-manager#6]
Hi, i'm trying to use the RtlSdrManager from nuget and from the demo in VS2019 and 2022, in a .net CORE 3.1 console app, but when is called any function from the manager, it throws the following exception: 
"Unable to load DLL 'librtlsdr' or one of its dependencies: The specified module could not be found. (0x8007007E)"

**Comment by rzoltan** [comment]
After some digging I have found the solution:
1. Get the latest package form here (32bit/64bit depending on your application): https://ftp.osmocom.org/binaries/windows/rtl-sdr/
2. Unzip the following dlls: librtlsdr.dll, libusb-1.0.dll
3. Copy them into your debug or release folder AND the trick on win10!! right click, advanced, unblock
4. Happy decoding! :)

**Comment by nathan-newman6519** [comment]
This solution is not working for me.  I have a .net core 3.1 app that I copied the dlls into the debug folder and it still can not find them.  I also tried to add them to the solution and VS is telling me they are unsupported.  Is there something specific I need to install?
